# Generated by Django 5.2.3 on 2025-06-20 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemonAPI', '0003_alter_cart_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['id'], 'verbose_name': 'Elemento del menú', 'verbose_name_plural': 'Elementos del menú'},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='idx_cart_user'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'MenuItem'], name='idx_cart_user_item'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['MenuItem'], name='idx_cart_menuitem'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', '-created_at'], name='idx_cart_user_recent'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='idx_category_title_lookup'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='idx_category_slug'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title', 'created_at'], name='idx_category_title_created'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['price'], name='idx_menuitem_price_filter'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['featured'], name='idx_menuitem_category'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['featured', 'price'], name='idx_menuitem_category_price'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['title'], name='idx_menuitem_title_search'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['available'], name='idx_menuitem_available'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['available', 'featured', 'price'], name='idx_menuitem_filters'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['-price'], name='idx_menuitem_price_desc'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='idx_order_user'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-date'], name='idx_order_user_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_crew'], name='idx_order_delivery_crew'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'delivery_crew'], name='idx_order_status_crew'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-date'], name='idx_order_date_desc'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-date'], name='idx_order_status_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='idx_order_user_status'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='idx_orderitem_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['menuitem'], name='idx_orderitem_menuitem'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'menuitem'], name='idx_orderitem_order_menu'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['menuitem', 'unit_price'], name='idx_orderitem_menu_price'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order'], name='idx_history_order'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['status'], name='idx_history_status'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order', '-created_at'], name='idx_history_order_date'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['changed_by'], name='idx_history_changed_by'),
        ),
    ]
